"""Shared constants across the Aion SDK.

This package re-exports the A2A extension constants so callers can use a
single stable import path:

``from aion.shared.constants import ...``
"""

from .a2a import (
    CARD_ACTION_EVENT_PAYLOAD_SCHEMA_V1,
    CARDS_EXTENSION_URI_V1,
    CARDS_MEDIA_TYPE,
    CARDS_PAYLOAD_SCHEMA_V1,
    COMMAND_EVENT_PAYLOAD_SCHEMA_V1,
    DISTRIBUTION_EXTENSION_URI_V1,
    EVENT_EXTENSION_URI_V1,
    MESSAGE_EVENT_PAYLOAD_SCHEMA_V1,
    MESSAGING_EXTENSION_URI_V1,
    REACTION_EVENT_PAYLOAD_SCHEMA_V1,
    SOURCE_SYSTEM_EVENT_PAYLOAD_SCHEMA_V1,
    TRACEABILITY_EXTENSION_URI_V1,
)

__all__ = [
    "DISTRIBUTION_EXTENSION_URI_V1",
    "CARDS_EXTENSION_URI_V1",
    "CARDS_PAYLOAD_SCHEMA_V1",
    "CARDS_MEDIA_TYPE",
    "CARD_ACTION_EVENT_PAYLOAD_SCHEMA_V1",
    "EVENT_EXTENSION_URI_V1",
    "MESSAGING_EXTENSION_URI_V1",
    "MESSAGE_EVENT_PAYLOAD_SCHEMA_V1",
    "REACTION_EVENT_PAYLOAD_SCHEMA_V1",
    "COMMAND_EVENT_PAYLOAD_SCHEMA_V1",
    "SOURCE_SYSTEM_EVENT_PAYLOAD_SCHEMA_V1",
    "TRACEABILITY_EXTENSION_URI_V1",
]
