"""Shared constants across the Aion SDK."""

from .a2a import (
    CARDS_EXTENSION_URI_V1,
    CARDS_MEDIA_TYPE,
    CARDS_PAYLOAD_SCHEMA_V1,
    DISTRIBUTION_EXTENSION_URI_V1,
    EVENT_EXTENSION_URI_V1,
    MESSAGING_EXTENSION_URI_V1,
    TRACEABILITY_EXTENSION_URI_V1,
)

__all__ = [
    "DISTRIBUTION_EXTENSION_URI_V1",
    "CARDS_EXTENSION_URI_V1",
    "CARDS_PAYLOAD_SCHEMA_V1",
    "CARDS_MEDIA_TYPE",
    "EVENT_EXTENSION_URI_V1",
    "MESSAGING_EXTENSION_URI_V1",
    "TRACEABILITY_EXTENSION_URI_V1",
]
