"""Tests for file storage: StubFileStorageBackend, FileUploadManager, A2AFileTransformer.

Focus areas:
  StubFileStorageBackend:
    - generate_uri with/without mime_type and context_id
    - upload is a no-op (does not raise)
    - delete is a no-op
    - URI format matches expected pattern

  FileUploadManager:
    - schedule() returns URI and starts background task
    - wait() only waits for requested URIs
    - drain() waits for all pending
    - delete() cancels pending / calls backend delete
    - pending_count tracks correctly
    - _upload_safe absorbs exceptions

  A2AFileTransformer:
    - is_active reflects upload_manager presence
    - transform_event: no-op when no manager
    - transform_event: transforms status event parts (raw -> url)
    - transform_event: transforms artifact event parts
    - transform_event: skips events with no raw parts
    - transform_message: transforms raw parts
    - transform_message: no-op with no parts
    - wait_upload=True triggers wait() call
    - drain() delegates to upload_manager
    - pending_count delegates
"""

import asyncio
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from a2a.types import (
    Artifact,
    Message,
    Part,
    Role,
    TaskArtifactUpdateEvent,
    TaskState,
    TaskStatus,
    TaskStatusUpdateEvent,
)

from aion.server.files.a2a.part_transformer import A2AFileTransformer
from aion.server.files.storage.backends.stub import StubFileStorageBackend
from aion.server.files.storage.manager import FileUploadManager

class TestStubFileStorageBackend:
    def _backend(self):
        return StubFileStorageBackend()

    def test_generate_uri_returns_two_strings(self):
        """generate_uri returns a tuple of (file_id, uri) as non-empty strings."""
        backend = self._backend()
        file_id, uri = backend.generate_uri()
        assert isinstance(file_id, str) and file_id
        assert isinstance(uri, str) and uri

    def test_generate_uri_different_file_ids(self):
        """Each call to generate_uri produces a unique file ID."""
        backend = self._backend()
        id1, _ = backend.generate_uri()
        id2, _ = backend.generate_uri()
        assert id1 != id2

    def test_generate_uri_without_context_id(self):
        """Generated URI contains file_id but not context_id when context_id is omitted."""
        backend = self._backend()
        file_id, uri = backend.generate_uri(mime_type="image/png")
        assert file_id in uri
        assert "ctx" not in uri  # no context_id in path

    def test_generate_uri_with_context_id(self):
        """Generated URI includes context_id when provided."""
        backend = self._backend()
        _, uri = backend.generate_uri(mime_type="image/png", context_id="ctx-abc")
        assert "ctx-abc" in uri

    def test_generate_uri_base_url_prefix(self):
        """Generated URI starts with the backend's BASE_URI."""
        backend = self._backend()
        _, uri = backend.generate_uri()
        assert uri.startswith(StubFileStorageBackend.BASE_URI)

    async def test_upload_does_not_raise(self):
        """upload is a no-op and does not raise exceptions."""
        backend = self._backend()
        file_id, _ = backend.generate_uri(mime_type="text/plain")
        await backend.upload(file_id=file_id, data=b"hello", mime_type="text/plain")

    async def test_delete_does_not_raise(self):
        """delete is a no-op and does not raise exceptions."""
        backend = self._backend()
        file_id, _ = backend.generate_uri()
        await backend.delete(file_id=file_id)

    async def test_delete_with_context_id_does_not_raise(self):
        """delete accepts context_id parameter without raising exceptions."""
        backend = self._backend()
        file_id, _ = backend.generate_uri(context_id="ctx-1")
        await backend.delete(file_id=file_id, context_id="ctx-1")

class TestFileUploadManager:
    def _backend(self):
        backend = MagicMock(spec=StubFileStorageBackend)
        backend.generate_uri.return_value = ("file-id-1", "https://stub/files/file-id-1")
        backend.upload = AsyncMock(return_value=None)
        backend.delete = AsyncMock(return_value=None)
        return backend

    def _manager(self, backend=None):
        return FileUploadManager(backend=backend or self._backend())

    async def test_schedule_returns_uri(self):
        """schedule returns the URI generated by the backend."""
        backend = self._backend()
        backend.generate_uri.return_value = ("id1", "https://example.com/id1")
        mgr = self._manager(backend)
        uri = mgr.schedule(data=b"data", mime_type="text/plain")
        assert uri == "https://example.com/id1"

    async def test_schedule_increments_pending_count(self):
        """schedule increments pending_count before the upload task completes."""
        backend = self._backend()
        backend.upload = AsyncMock(return_value=None)
        event = asyncio.Event()

        async def _slow_upload(**kw):
            await event.wait()

        backend.upload = _slow_upload
        mgr = self._manager(backend)

        mgr.schedule(data=b"x", mime_type="text/plain")
        assert mgr.pending_count == 1

    async def test_schedule_clears_pending_after_upload(self):
        """pending_count returns to 0 after uploaded file completes."""
        backend = self._backend()
        mgr = self._manager(backend)
        uri = mgr.schedule(data=b"data", mime_type="text/plain")
        await mgr.wait([uri])
        await asyncio.sleep(0)
        assert mgr.pending_count == 0

    async def test_wait_for_specific_uri(self):
        """wait completes when the specified URI has finished uploading."""
        backend = self._backend()
        mgr = self._manager(backend)
        uri = mgr.schedule(data=b"data", mime_type="text/plain")
        await mgr.wait([uri])

    async def test_wait_ignores_unknown_uris(self):
        """wait does not raise for URIs that were never scheduled."""
        mgr = self._manager()
        await mgr.wait(["https://unknown.example.com/file"])

    async def test_drain_waits_for_all(self):
        """drain waits for all pending uploads to complete."""
        backend = self._backend()
        mgr = self._manager(backend)
        for i in range(3):
            backend.generate_uri.return_value = (f"id{i}", f"https://stub/{i}")
            mgr.schedule(data=b"x", mime_type="text/plain")

        await mgr.drain()
        assert mgr.pending_count == 0

    async def test_drain_noop_when_no_pending(self):
        """drain does not raise when there are no pending uploads."""
        mgr = self._manager()
        await mgr.drain()

    async def test_delete_cancels_pending_task(self):
        """delete cancels a pending upload task before completion."""
        backend = self._backend()
        event = asyncio.Event()

        async def _slow(**kw):
            await event.wait()

        backend.upload = _slow
        mgr = self._manager(backend)
        uri = mgr.schedule(data=b"x", mime_type="text/plain")

        await mgr.delete(uri)
        for _ in range(5):
            await asyncio.sleep(0)
        assert uri not in mgr._pending

    async def test_delete_calls_backend_delete(self):
        """delete delegates to backend.delete after upload completes."""
        backend = self._backend()
        mgr = self._manager(backend)
        uri = mgr.schedule(data=b"x", mime_type="text/plain")
        await mgr.wait([uri])
        await mgr.delete(uri)
        backend.delete.assert_called_once()

    async def test_upload_safe_absorbs_exceptions(self):
        """_upload_safe catches backend upload exceptions without propagating them."""
        backend = self._backend()
        backend.upload = AsyncMock(side_effect=RuntimeError("boom"))
        mgr = self._manager(backend)
        uri = mgr.schedule(data=b"x", mime_type="text/plain")
        await mgr.wait([uri])

def _make_part_raw(data: bytes = b"hello", media_type: str = "text/plain") -> Part:
    return Part(raw=data, media_type=media_type)


def _make_part_text(text: str = "hello") -> Part:
    return Part(text=text)


def _make_status_event(parts: list[Part] | None = None, context_id: str = "ctx-1") -> TaskStatusUpdateEvent:
    msg = Message(role=Role.ROLE_AGENT, parts=parts or []) if parts is not None else None
    return TaskStatusUpdateEvent(
        task_id="task-1",
        context_id=context_id,
        status=TaskStatus(state=TaskState.TASK_STATE_WORKING, message=msg),
    )


def _make_artifact_event(parts: list[Part], context_id: str = "ctx-1") -> TaskArtifactUpdateEvent:
    artifact = Artifact(artifact_id="art-1", parts=parts)
    return TaskArtifactUpdateEvent(
        task_id="task-1",
        context_id=context_id,
        artifact=artifact,
    )


def _make_message(parts: list[Part] | None = None, context_id: str = "ctx-1") -> Message:
    return Message(role=Role.ROLE_USER, parts=parts or [], context_id=context_id)

class TestA2AFileTransformer:
    def _mock_manager(self):
        mgr = MagicMock(spec=FileUploadManager)
        mgr.schedule.return_value = "https://stub/files/abc"
        mgr.wait = AsyncMock()
        mgr.drain = AsyncMock()
        mgr.pending_count = 0
        return mgr

    def test_is_active_true_with_manager(self):
        """is_active returns True when upload_manager is set."""
        t = A2AFileTransformer(upload_manager=self._mock_manager())
        assert t.is_active is True

    def test_is_active_false_without_manager(self):
        """is_active returns False when upload_manager is None."""
        t = A2AFileTransformer(upload_manager=None)
        assert t.is_active is False

    def test_upload_manager_property(self):
        """upload_manager property returns the configured manager."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        assert t.upload_manager is mgr

    async def test_transform_event_noop_without_manager(self):
        """transform_event returns event unchanged when no upload_manager is configured."""
        t = A2AFileTransformer(upload_manager=None)
        event = _make_status_event(parts=[_make_part_raw()])
        result = await t.transform_event(event)
        assert result is event

    async def test_transform_status_event_replaces_raw_part(self):
        """transform_event replaces raw binary parts with uploaded file URLs in status events."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        event = _make_status_event(parts=[_make_part_raw(b"image data", "image/png")])

        result = await t.transform_event(event)

        assert isinstance(result, TaskStatusUpdateEvent)
        new_parts = list(result.status.message.parts)
        assert len(new_parts) == 1
        assert new_parts[0].url == "https://stub/files/abc"
        assert new_parts[0].raw is None or new_parts[0].raw == b""

    async def test_transform_status_event_skips_non_raw_parts(self):
        """transform_event leaves non-raw parts unchanged in status events."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        event = _make_status_event(parts=[_make_part_text("hello")])

        result = await t.transform_event(event)
        assert result is event

    async def test_transform_status_event_no_message_returns_unchanged(self):
        """transform_event returns status event unchanged when message is None."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        event = TaskStatusUpdateEvent(
            task_id="t1",
            context_id="ctx-1",
            status=TaskStatus(state=TaskState.TASK_STATE_WORKING),
        )
        result = await t.transform_event(event)
        assert result is event

    async def test_transform_artifact_event_replaces_raw_part(self):
        """transform_event replaces raw binary parts with uploaded URLs in artifact events."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        event = _make_artifact_event(parts=[_make_part_raw(b"bytes", "application/pdf")])

        result = await t.transform_event(event)

        assert isinstance(result, TaskArtifactUpdateEvent)
        new_parts = list(result.artifact.parts)
        assert new_parts[0].url == "https://stub/files/abc"

    async def test_transform_artifact_event_empty_parts_unchanged(self):
        """transform_event returns artifact event unchanged when parts list is empty."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        event = _make_artifact_event(parts=[])
        result = await t.transform_event(event)
        assert result is event

    async def test_transform_message_replaces_raw_parts(self):
        """transform_message replaces raw parts with uploaded file URLs."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        msg = _make_message(parts=[_make_part_raw(b"data", "text/plain")])

        result = await t.transform_message(msg)

        new_parts = list(result.parts)
        assert new_parts[0].url == "https://stub/files/abc"

    async def test_transform_message_noop_without_manager(self):
        """transform_message returns message unchanged when no upload_manager is configured."""
        t = A2AFileTransformer(upload_manager=None)
        msg = _make_message(parts=[_make_part_raw()])
        result = await t.transform_message(msg)
        assert result is msg

    async def test_transform_message_noop_no_parts(self):
        """transform_message returns message unchanged when parts list is empty."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        msg = _make_message(parts=[])
        result = await t.transform_message(msg)
        assert result is msg

    async def test_wait_upload_true_calls_wait(self):
        """transform_event with wait_upload=True calls manager's wait method."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        event = _make_status_event(parts=[_make_part_raw()])

        await t.transform_event(event, wait_upload=True)

        mgr.wait.assert_called_once()

    async def test_wait_upload_false_does_not_call_wait(self):
        """transform_event with wait_upload=False does not call manager's wait method."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        event = _make_status_event(parts=[_make_part_raw()])

        await t.transform_event(event, wait_upload=False)

        mgr.wait.assert_not_called()

    async def test_drain_delegates_to_manager(self):
        """drain delegates to the upload_manager's drain method."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        await t.drain()
        mgr.drain.assert_called_once()

    async def test_drain_noop_without_manager(self):
        """drain does not raise when no upload_manager is configured."""
        t = A2AFileTransformer(upload_manager=None)
        await t.drain()

    def test_pending_count_with_manager(self):
        """pending_count returns the manager's pending count when manager is set."""
        mgr = self._mock_manager()
        mgr.pending_count = 5
        t = A2AFileTransformer(upload_manager=mgr)
        assert t.pending_count == 5

    def test_pending_count_without_manager(self):
        """pending_count returns 0 when no upload_manager is configured."""
        t = A2AFileTransformer(upload_manager=None)
        assert t.pending_count == 0

    async def test_mime_type_guessed_from_filename(self):
        """transform_message guesses mime type from filename when media_type is not set."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        part = Part(raw=b"data", filename="document.pdf")
        msg = _make_message(parts=[part])
        await t.transform_message(msg)
        call_kwargs = mgr.schedule.call_args[1]
        assert "pdf" in call_kwargs.get("mime_type", "")

    async def test_fallback_mime_type_octet_stream(self):
        """transform_message falls back to application/octet-stream when mime type cannot be determined."""
        mgr = self._mock_manager()
        t = A2AFileTransformer(upload_manager=mgr)
        part = Part(raw=b"data")
        msg = _make_message(parts=[part])
        await t.transform_message(msg)
        call_kwargs = mgr.schedule.call_args[1]
        assert call_kwargs.get("mime_type") == "application/octet-stream"


class TestFileUploadManagerFromSettings:
    def test_returns_none_when_no_backend_configured(self):
        """from_settings returns None when file_storage_backend is not configured."""
        with patch("aion.shared.settings.app_settings") as mock:
            mock.file_storage_backend = None
            result = FileUploadManager.from_settings()
            assert result is None

    def test_returns_manager_for_stub_backend(self):
        """from_settings returns a FileUploadManager when backend is 'stub'."""
        with patch("aion.shared.settings.app_settings") as mock:
            mock.file_storage_backend = "stub"
            result = FileUploadManager.from_settings()
            assert isinstance(result, FileUploadManager)

    def test_raises_for_unknown_backend(self):
        """from_settings raises ValueError for unknown storage backend names."""
        with patch("aion.shared.settings.app_settings") as mock:
            mock.file_storage_backend = "s3"
            with pytest.raises(ValueError, match="Unknown storage backend"):
                FileUploadManager.from_settings()

class TestFileUploadManagerContextId:
    def _backend(self):
        backend = MagicMock(spec=StubFileStorageBackend)
        backend.generate_uri.return_value = ("file-id-1", "https://stub/files/file-id-1")
        backend.upload = AsyncMock(return_value=None)
        backend.delete = AsyncMock(return_value=None)
        return backend

    async def test_schedule_passes_context_id_to_backend(self):
        """schedule passes context_id to backend's generate_uri method."""
        backend = self._backend()
        mgr = FileUploadManager(backend=backend)
        mgr.schedule(data=b"x", mime_type="text/plain", context_id="ctx-42")
        backend.generate_uri.assert_called_once_with(mime_type="text/plain", context_id="ctx-42")

    async def test_delete_passes_context_id_to_backend(self):
        """delete passes context_id to backend's delete method."""
        backend = self._backend()
        mgr = FileUploadManager(backend=backend)
        uri = mgr.schedule(data=b"x", mime_type="text/plain")
        await mgr.wait([uri])
        await mgr.delete(uri, context_id="ctx-99")
        backend.delete.assert_called_once()
        _, kwargs = backend.delete.call_args
        assert kwargs.get("context_id") == "ctx-99"

    async def test_delete_never_scheduled_uri_does_not_raise(self):
        """delete does not raise or call backend for URIs that were never scheduled."""
        backend = self._backend()
        mgr = FileUploadManager(backend=backend)
        await mgr.delete("https://never-scheduled.example.com/file")
        backend.delete.assert_not_called()

    async def test_uri_to_file_id_cleaned_up_after_delete(self):
        """delete removes the URI from internal tracking after backend deletion."""
        backend = self._backend()
        mgr = FileUploadManager(backend=backend)
        uri = mgr.schedule(data=b"x", mime_type="text/plain")
        await mgr.wait([uri])
        await mgr.delete(uri)
        assert uri not in mgr._uri_to_file_id
